### ISSUE TITLE
error.handling.codes doesn't overwrite

### ISSUE THREAD

**Issue by yonchev** [wimdeblauwe/error-handling-spring-boot-starter#60] opened 2023-01-08 13:20 UTC
I try to wrap IllegalArgumentException with 
error.handling.codes.java.lang.IllegalArgumentException=ILLEGAL_ARGUMENT as is written in documentation, but result is still tomcat error page not JSON response. My test is to put illegal simbols like **1'||(** on Integer @RequestParam. 

Do you have any idea how I can turn it to generic JSON respons, without trace information, like the others?

SpringBoot 2.7.6 with 3.3.0 error-handling

**Comment by wimdeblauwe** [comment] 2023-01-09 10:06
Can you read https://wimdeblauwe.github.io/error-handling-spring-boot-starter/current/#handle-non-rest-controller-exceptions and see if this applies to what you are trying to do?

**Comment by wimdeblauwe** [comment] 2023-01-09 19:07
When I test this, I see I get this by default:

```
{
  "code": "ARGUMENT_TYPE_MISMATCH",
  "message": "Failed to convert value of type 'java.lang.String' to required type 'java.lang.Integer'; For input string: \"1'||(\"",
  "expectedType": "java.lang.Integer",
  "property": "integer",
  "rejectedValue": "1'||("
}
```

Using this endpoint:

```
    @GetMapping("/request-param")
    void test(@RequestParam Integer integer) {

    }
```

This is because of this default mapping:

```
error.handling.codes.org.springframework.web.method.annotation.MethodArgumentTypeMismatchException=ARGUMENT_TYPE_MISMATCH
```

If you can send me a test case, I can have another look.

**Comment by yonchev** [comment] 2023-01-09 20:19
This is exactly what I want but in mine case I got Tomcat error. Here is mine test endpoint




    @GetMapping(path = "/test", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<?> testEndPoint(@RequestParam("page") Integer page) {
        return ResponseEntity.ok().build();
    }



with or without error.handling.codes maps the result doesn't change and I can't figure out where I'm going wrong

**Comment by wimdeblauwe** [comment] 2023-01-09 20:26
Could you try to create a small test program that shows the problem so I can debug it further?

**Comment by yonchev** [comment] 2023-01-09 21:10
[test.zip](https://github.com/wimdeblauwe/error-handling-spring-boot-starter/files/10376859/test.zip)

here it is

**Comment by wimdeblauwe** [comment] 2023-01-10 06:19
When I run your application and get the request using the IntelliJ HTTP client, I get this:

```
{
  "code": "ARGUMENT_TYPE_MISMATCH",
  "message": "Failed to convert value of type 'java.lang.String' to required type 'java.lang.Integer'; nested exception is java.lang.NumberFormatException: For input string: \"1'||(\"",
  "expectedType": "java.lang.Integer",
  "property": "page",
  "rejectedValue": "1'||("
}
```

When I change the `application.yaml` to:
```
error:
  handling:
    codes:
      java.lang.IllegalArgumentException: ILLEGAL_ARGUMENT
      org.springframework.web.method.annotation.MethodArgumentTypeMismatchException: ILLEGAL_ARGUMENT
```

Then I get:

```
{
  "code": "ILLEGAL_ARGUMENT",
  "message": "Failed to convert value of type 'java.lang.String' to required type 'java.lang.Integer'; nested exception is java.lang.NumberFormatException: For input string: \"1'||(\"",
  "expectedType": "java.lang.Integer",
  "property": "page",
  "rejectedValue": "1'||("
}
```

So I am afraid I don't see any issue.

**Comment by yonchev** [comment] 2023-01-10 10:34
Can you try with 
http://localhost:8888/api/test?page=|

**Comment by wimdeblauwe** [comment] 2023-01-10 19:05
Same:

```
{
  "code": "ILLEGAL_ARGUMENT",
  "message": "Failed to convert value of type 'java.lang.String' to required type 'java.lang.Integer'; nested exception is java.lang.NumberFormatException: For input string: \"|\"",
  "expectedType": "java.lang.Integer",
  "property": "page",
  "rejectedValue": "|"
}
```

I also tested in the browser and same result. And you get a different result using this test application as well? Or are you only testing in your actual application?

**Comment by yonchev** [comment] 2023-01-10 20:08
Apparently the problem is local only for me, but I don't understand why. Both my real application and test app are like that. Anyway, thanks for your time, I'll look for the reason

**Comment by wimdeblauwe** [comment] 2023-06-08 06:23
Closing as the issue does not seem reproducible for me.

**Closed by wimdeblauwe** 2023-06-08 06:23 UTC
